version: '3.8'

services:
  metrics_api_dev:
    container_name: metrics_api_dev
    image: metrics_api_dev:1.0.0
    build:
      context: .
    ports:
      - ${PORT}:${PORT}
    depends_on: 
      - metrics_mongodb
    volumes:
      - ./:/app
    command: npm run start:dev
    restart: unless-stopped

  metrics_mongodb:
    container_name: ${DATABASE_HOST}
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USERNAME} 
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD} 
    expose:
      - ${DATABASE_PORT}
    volumes:
      - ./mongo-data:/data/db 
    restart: unless-stopped
    
networks:
  default:
    driver: bridge
